AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'vendor/**/.*'
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
Naming/VariableNumber:
  Exclude:
    - 'test/**/*'
